// File: lib/features/dashboard/presentation/bloc/dashboard_bloc.dart
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:injectable/injectable.dart';
import 'package:rural_health_app/features/dashboard/data/models/dashboard_models.dart';
import 'package:rural_health_app/features/dashboard/domain/repositories/i_dashboard_repository.dart';

part 'dashboard_event.dart';
part 'dashboard_state.dart';
part 'dashboard_bloc.freezed.dart'; // Generated by freezed

@injectable
class DashboardBloc extends Bloc<DashboardEvent, DashboardState> {
  final IDashboardRepository _dashboardRepository;

  DashboardBloc(this._dashboardRepository) : super(const DashboardState.initial()) {
    on<FetchDashboardDataRequested>(_onFetchDashboardDataRequested);
    on<RefreshDashboardDataRequested>(_onRefreshDashboardDataRequested);
  }

  Future<void> _onFetchDashboardDataRequested(
      FetchDashboardDataRequested event, Emitter<DashboardState> emit) async {
    emit(const DashboardState.loading());
    await _fetchData(emit);
  }

  Future<void> _onRefreshDashboardDataRequested(
      RefreshDashboardDataRequested event, Emitter<DashboardState> emit) async {
    // Can emit a specific state for refreshing if UI needs to behave differently
    // For now, just re-trigger loading.
    emit(const DashboardState.loading());
    await _fetchData(emit);
  }

  Future<void> _fetchData(Emitter<DashboardState> emit) async {
    final result = await _dashboardRepository.getDashboardData();
    result.fold(
      (failure) => emit(DashboardState.error(message: failure.message)),
      (dataTuple) {
        final dashboardData = dataTuple.$1;
        final isStale = dataTuple.$2;
        emit(DashboardState.loaded(dashboardData: dashboardData, isStale: isStale));
      },
    );
  }
}
