// File: lib/features/auth/presentation/bloc/auth_bloc.dart
import 'dart:async';

import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:injectable/injectable.dart';
import 'package:rural_health_app/features/auth/data/models/user_model.dart';
import 'package:rural_health_app/features/auth/domain/repositories/i_auth_repository.dart';

part 'auth_event.dart';
part 'auth_state.dart';
part 'auth_bloc.freezed.dart'; // Generated by freezed

@injectable
class AuthBloc extends Bloc<AuthEvent, AuthState> {
  final IAuthRepository _authRepository;
  StreamSubscription<UserModel?>? _authStatusSubscription;

  AuthBloc(this._authRepository) : super(const AuthState.initial()) {
    on<LoginRequested>(_onLoginRequested);
    on<LogoutRequested>(_onLogoutRequested);
    on<_AuthStatusChanged>(_onAuthStatusChanged);

    // Subscribe to authentication status changes from the repository
    _authStatusSubscription = _authRepository.authStatusChanges.listen((user) {
      add(_AuthStatusChanged(user));
    });
  }

  Future<void> _onLoginRequested(
      LoginRequested event, Emitter<AuthState> emit) async {
    emit(const AuthState.loading());
    final result = await _authRepository.login(
        username: event.username, password: event.password);
    result.fold(
      (failure) => emit(AuthState.failure(message: failure.message)),
      (user) => emit(AuthState.authenticated(user: user)),
    );
  }

  Future<void> _onLogoutRequested(
      LogoutRequested event, Emitter<AuthState> emit) async {
    // No loading state needed for logout typically, but can be added if API call is slow
    final result = await _authRepository.logout();
    result.fold(
      (failure) => emit(AuthState.failure(message: failure.message)),
      (_) => emit(const AuthState.unauthenticated()),
    );
  }

  void _onAuthStatusChanged(_AuthStatusChanged event, Emitter<AuthState> emit) {
    if (event.user != null) {
      emit(AuthState.authenticated(user: event.user!));
    } else {
      emit(const AuthState.unauthenticated());
    }
  }

  @override
  Future<void> close() {
    _authStatusSubscription?.cancel();
    // Dispose the repository if it has a dispose method and GetIt is configured for it
    // (_authRepository as AuthRepository).dispose(); // Example, ensure type safety
    return super.close();
  }
}
