// File: lib/features/patient_registration/presentation/bloc/patient_registration_bloc.dart
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:injectable/injectable.dart';
import 'package:rural_health_app/features/patient_registration/data/models/patient_registration_model.dart';
import 'package:rural_health_app/features/patient_registration/domain/repositories/i_patient_repository.dart';
import 'package:rural_health_app/core/platform/network_info.dart'; // For checking connectivity status

part 'patient_registration_event.dart';
part 'patient_registration_state.dart';
part 'patient_registration_bloc.freezed.dart'; // Generated by freezed

const int totalRegistrationSteps = 4; // Define total number of steps in your form

@injectable
class PatientRegistrationBloc
    extends Bloc<PatientRegistrationEvent, PatientRegistrationState> {
  final IPatientRepository _patientRepository;
  final INetworkInfo _networkInfo;

  PatientRegistrationBloc(this._patientRepository, this._networkInfo)
      : super(const PatientRegistrationState.initial()) {
    on<InitializeForm>(_onInitializeForm);
    on<UpdateFormData>(_onUpdateFormData);
    on<NextStep>(_onNextStep);
    on<GoToStep>(_onGoToStep);
    on<PreviousStep>(_onPreviousStep);
    on<SubmitRegistration>(_onSubmitRegistration);
    on<SyncQueuedRegistrations>(_onSyncQueuedRegistrations);
  }

  void _onInitializeForm(
      InitializeForm event, Emitter<PatientRegistrationState> emit) {
    emit(PatientRegistrationState.formInProgress(
      currentPayload: PatientRegistrationPayload.initial(),
      currentStep: 0,
    ));
  }

  void _onUpdateFormData(
      UpdateFormData event, Emitter<PatientRegistrationState> emit) {
    if (state is PatientRegistrationFormInProgress) {
      final currentState = state as PatientRegistrationFormInProgress;
      emit(currentState.copyWith(currentPayload: event.updatedPayload));
    }
  }

  void _onNextStep(NextStep event, Emitter<PatientRegistrationState> emit) {
    if (state is PatientRegistrationFormInProgress) {
      final currentState = state as PatientRegistrationFormInProgress;
      if (currentState.currentStep < totalRegistrationSteps - 1) {
        emit(currentState.copyWith(currentStep: currentState.currentStep + 1));
      }
    }
  }

  void _onGoToStep(GoToStep event, Emitter<PatientRegistrationState> emit) {
    if (state is PatientRegistrationFormInProgress) {
      final currentState = state as PatientRegistrationFormInProgress;
      if (event.step >= 0 && event.step < totalRegistrationSteps) {
        emit(currentState.copyWith(currentStep: event.step));
      }
    }
  }

  void _onPreviousStep(
      PreviousStep event, Emitter<PatientRegistrationState> emit) {
    if (state is PatientRegistrationFormInProgress) {
      final currentState = state as PatientRegistrationFormInProgress;
      if (currentState.currentStep > 0) {
        emit(currentState.copyWith(currentStep: currentState.currentStep - 1));
      }
    }
  }

  Future<void> _onSubmitRegistration(
      SubmitRegistration event, Emitter<PatientRegistrationState> emit) async {
    if (state is PatientRegistrationFormInProgress) {
      final currentState = state as PatientRegistrationFormInProgress;
      emit(currentState.copyWith(isSubmitting: true, submissionMessage: null));

      final payloadToSubmit = currentState.currentPayload;
      final result = await _patientRepository.registerPatient(payloadToSubmit);

      final bool isOnline = await _networkInfo.isConnected;

      result.fold(
        (failure) {
          emit(PatientRegistrationState.submissionFailure(
            errorMessage: failure.message,
            payloadOnError: payloadToSubmit,
            currentStepOnError: currentState.currentStep,
          ));
        },
        (_) async {
          final message = isOnline
              ? 'Patient registered successfully!'
              : 'Registration queued for offline submission.';
          emit(PatientRegistrationState.submissionSuccess(
            message: message,
            submittedPayload: payloadToSubmit,
          ));
          // Could also re-initialize form here or let UI handle navigation
           add(const InitializeForm()); // Reset form after successful submission
        },
      );
    }
  }

  Future<void> _onSyncQueuedRegistrations(
    SyncQueuedRegistrations event, Emitter<PatientRegistrationState> emit) async {
    emit(const PatientRegistrationState.syncingQueuedData());
    final result = await _patientRepository.syncQueuedRegistrations();

    await result.fold(
      (failure) async {
        // If sync fails (e.g. no network), revert to previous state or an error state.
        // For simplicity, fetching current form state or going initial.
        // A more robust solution would keep the form state if it was in progress.
        final currentQueued = await _patientRepository.getQueuedRegistrations();
        emit(PatientRegistrationState.syncCompleted(
            summary: SyncSummary(totalItems: 0, successfulSyncs: 0, failedSyncs: 0), // Dummy summary on failure
            remainingInQueue: currentQueued.getOrElse(() => [])
        ));
         // Optionally show error: emit(PatientRegistrationState.submissionFailure(errorMessage: failure.message...))
         // For now, just log or let UI show a generic sync issue.
      },
      (summary) async {
        final currentQueued = await _patientRepository.getQueuedRegistrations();
        emit(PatientRegistrationState.syncCompleted(
            summary: summary,
            remainingInQueue: currentQueued.getOrElse(() => [])
        ));
      }
    );
    // Potentially revert to the form in progress state if it was active
    // This example assumes sync is more of a background task indication.
    // If user was on the form, you might want to restore that state.
    // add(const InitializeForm()); // Or restore previous form state
  }
}
